import { IEvent } from "../Interface/eventInterface"

export const eventList: IEvent[] = [
    {
        id: 0,
        title: "BOOTCAMP",
        subTitle: "YRA Global Research Bootcamp 2026 (Cohort 1)",
        shortDesc: "Intensive training in research skills.",
        shortSubTitle: "YRA Global Research Bootcamp 2026",
        desc: "Intensive research training designed to equip researchers with essential knowledge and practical skills from idea development to publication.",
        type: "TRAINING",
        programme: "YRA Programme",
        shortDate: "20 Aug",
        longDate: "20 August 2026",
        mode: "Online",
        duration: "4 Weeks",
        regFee: "₦15,000",
    },
    {
        id: 1,
        title: "SLR",
        subTitle: "How to Write a Systematic Literature Review",
        shortSubTitle: "How to Write a Systematic Literature Review",
        shortDesc: "Practical SLR writing and publication session.",
        desc: "Practical session on systematic literature review design, searching, screening, synthesis and publication.",
        type: "SEMINAR",
        programme: "YRA Programme",
        shortDate: "30 Aug",
        longDate: "30 August 2026",
        mode: "Online",
        duration: "1 Day",
        regFee: "₦5,000",
    },
    {
        id: 2,
        title: "SPSS",
        subTitle: "Data Analysis with SPSS for Researchers",
        shortSubTitle: "Data Analysis with SPSS for Researchers",
        shortDesc: "Hands-on statistical analysis workshop.",
        desc: "Hands-on workshop on selecting, running and interpreting common statistical analyses.",
        type: "WORKSHOP",
        programme: "YRA Programme",
        shortDate: "10 Sep",
        longDate: "10 September 2026",
        mode: "Online",
        duration: "2 Days",
        regFee: "₦7,500",
    },
];
